name: Update Git Tag

on:
  push:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update tag
        uses: actions/github-script@v7
        with:
          script: |
            const { GITHUB_REPOSITORY, GITHUB_SHA } = process.env;
            const ref = "tags/v1";
            await github.rest.git.updateRef({
              owner: GITHUB_REPOSITORY.split('/')[0],
              repo: GITHUB_REPOSITORY.split('/')[1],
              ref,
              sha: GITHUB_SHA,
              force: true,
            });